# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: processor-deploy
#   labels:
#     app: processor-app
#   annotations:
# spec:
#   selector:
#     matchLabels:
#       app: processor-app
#   replicas: 1
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 0
#   template:
#     metadata:
#       labels:
#         app: processor-app
#     spec:
#       containers:
#       - name: processor-1
#         image: registry.digitalocean.com/mapofzones/txs-processor:latest
#         env:
#           - name: rabbitmq
#             valueFrom:
#               secretKeyRef:
#                 name: devsecret
#                 key: processor_rabbitmq
#           - name: postgres
#             valueFrom:
#               secretKeyRef:
#                 name: devsecret
#                 key: processor_db
#         imagePullPolicy: Always
#         resources:
#           requests:
#             memory: "100Mi"
#             cpu: "100m"
#           limits:
#             memory: "256Mi"
#             cpu: "200m"
